name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.4'

    - name: Build with Gradle
      run: gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: TalkSync-APK
        path: app/build/outputs/apk/debug/*.apk

    - name: Delete Old Release
      if: github.ref == 'refs/heads/main'
      run: |
        gh release delete latest --cleanup-tag -y || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Version
      if: github.ref == 'refs/heads/main'
      id: extract_version
      run: |
        VERSION=$(grep -oP 'versionName "\K[^"]+' app/build.gradle)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Rename APK for permanent link
      if: github.ref == 'refs/heads/main'
      run: |
        mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/TalkSync_latest.apk

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        files: app/build/outputs/apk/debug/TalkSync_latest.apk
        tag_name: latest
        name: ${{ steps.extract_version.outputs.version }}
        body: |
          TalkSync APK (Автоматическая сборка)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
